### ISSUE TITLE
Hard coded child theme name

### ISSUE THREAD

**Issue by proweb** [yootheme/example-element#1]
I've created child theme as discribed in docs.

My child theme folder is `yootheme_vbik`
![image](https://user-images.githubusercontent.com/680073/29044115-988baede-7bc6-11e7-9b65-8ebdfb58444f.png)

So I created `builder` folder in child theme and extracted this repo in it

So my structure looks like this:
![image](https://user-images.githubusercontent.com/680073/29044025-3645fc2a-7bc6-11e7-9217-5292864cbf0b.png)

But if I'll try to create new element - I don't see any icon on it
![_583](https://user-images.githubusercontent.com/680073/29044492-67f2a67c-7bc8-11e7-8cea-32bd43156d99.png)

And in console I see wrong way to SVG icon
![image](https://user-images.githubusercontent.com/680073/29044445-25f16c5e-7bc8-11e7-8e92-6c75008fac2e.png)
the true way is `.../templates/yootheme_vbik/builder/pro-element/icon.svg`

So, how to fix it?

**Comment by janschoenherr** [comment]
You'll have to adjust the path to the icons here

https://github.com/yootheme/pro-element/blob/master/pro-element.js#L55
https://github.com/yootheme/pro-element/blob/master/pro-element.js#L58
