### ISSUE TITLE
Unclear what the purpose of content.php is

### ISSUE THREAD

**Issue by w-biggs** [yootheme/example-element#5]
The docs and the readme here don't make clear what the new content.php is for. It seems to be a duplicate of part of template.php... but I have no idea what I'm supposed to do with it. It's never mentioned in the docs or in the readme except that it "renders the content which is saved in the page"... but what's the difference between that and rendering "the actual front-end markup"?

**Comment by saschadube** [comment]
The `content.php` renders the markup which is saved in the Joomla article (or WordPress page respectively). It's a clean representation of the content with semantic markup and without any HTML classes. The saved content is used for the search in Joomla/WordPress and it's also the content which is left behind when you uninstall YOOtheme Pro. 

The other template files render the markup which is served to the client with all the HTML classes and style representations like slideshows, etc. Basically everything which depends on YOOtheme Pro like all the settings and UIkit dependencies.
