### ISSUE TITLE
element.php updates hook not working?

### ISSUE THREAD

**Issue by timchambers** [yootheme/example-element#6]
I created a custom builder element following the docs, and recently wanted to rename one of my props, so I added an 'updates' hook like this to the element.php file in the custom element's directory do so:

```php
<?php

return [

    'updates' => [

        '1.1.2' => function ($node, array $params) {

			if (isset($node->props['tag_slug'])) {
				$node->props['filter_tag_slugs'] = $node->props['tag_slug'];
				unset($node->props['tag_slug']);
			}

        },

    ],

];

```

However when I load pages that already had the custom element on them (with a value in the old prop named `tag_slug`, they don't get seem to be getting the new prop name. It seems this hook isn't firing at all. What am I doing wrong?

The `1.1.2` version number is my child theme's version number, but I assume that part doesn't matter?

I'm running Yootheme 1.20.6 as the parent theme.

**Comment by saschadube** [comment]
Currently element updates are tied to the updates of YOOtheme Pro. They don't have their own version numbers and can only be updated when the YOOtheme Pro version number changes.

The current version of YOOtheme Pro is `2.3.15`, so to apply your script with the next YOOtheme update set the number to `2.3.16` in the update hook.

We know that this isn't very nice and elements updates should be based on their own version number but that's the current status quo.
